# Change these first
owner: TeamGround # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Ground
    url: https://teamground.fr
  - name: Yolocracy
    url: https://yolocracy.org
  - name: Background
    url: https://offres.teamground.fr/backgrond
  - name: Crystal
    url: https://www.crystal.work


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Ground status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
